import math
# Game Settings
FLOOR_COLOR = (30, 30, 30)

# Video Settings
RESOLUTION = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60

# Player initial Position
PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.003
PLAYER_ROT_SPEED = 0.002
# Player Scaling
PLAYER_SIZE_SCALE = 60

# Mouse Settings
MOUSE_SENSITIVITY = 0.0001
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

# Raycast Settings
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS / 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

# Calculations for 3D Rendering
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH / NUM_RAYS

# Textures Settings
TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
